import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createGame, update, damageShip } from '../src/world.js';
import { createEnemy } from '../src/enemies.js';
import { damageEnemy } from '../src/hits.js';
import { CONFIG } from '../src/config.js';

test('the lethal boss hit replays the approach, sweeps the field, shows clear, and awards once', () => {
  const g = createGame({ scheme: 'hyper', seed: 4 });
  g.spawning = false; g.field.moons = []; g.field.dust = [];
  Object.assign(g.ship, { x: 0, y: -3000, vx: 600, vy: 0, glide: true });
  const boss = createEnemy('boss', 1, 220, -3000);
  const fodder = createEnemy('drifter', 1, -100, -3200);
  boss.speed = fodder.speed = 0;
  g.boss = boss; g.bossSpawned = true; g.enemies = [boss, fodder];
  for (let i = 0; i < 4; i++) update(g, 0.02, {});
  g.t = CONFIG.runTime - 0.001;
  damageEnemy(g, boss, boss.hp, { cause: 'wave' });
  assert.equal(g.state, 'finishing');
  assert.ok(!boss.dead && !fodder.dead, 'the explosion must wait for the slow final blow');
  const atHit = g.ship.x, hp = g.ship.hp, time = g.t, coins = g.coins;
  const kills = g.kills;
  g.offerQueue.push({ id: 'ram', slot: 'bow', r: 0 });
  g.ebullets.push({ x: g.ship.x, y: g.ship.y, vx: 0, vy: 0, dmg: 1000, life: 10 });
  assert.equal(damageShip(g, 1000, 0.9), false);
  update(g, 0.05, { dash: true, cursor: { x: 999, y: 999 } });
  assert.ok(g.ship.x < atHit, 'the actual recent approach is replayed, not a static freeze');
  assert.equal(g.ship.hp, hp);
  assert.equal(g.t, time, 'the finisher cannot cause a timeout');
  assert.equal(g.state, 'finishing');
  for (let i = 0; i < 40 && g.finale.phase === 'slow'; i++) update(g, 0.05, {});
  assert.equal(g.finale.phase, 'blast');
  assert.equal(g.timeScale, 1);
  assert.ok(boss.dead && fodder.dead);
  assert.equal(g.enemies.length, 0); assert.equal(g.ebullets.length, 0);
  assert.equal(g.kills, kills + 2);
  assert.ok(g.fx.particles.some(p => p.kind === 'finishDebris'));
  assert.equal(g.coins, coins, 'no early or duplicate clear reward');
  for (let i = 0; i < 60 && g.finale.phase === 'blast'; i++) update(g, 0.05, {});
  assert.equal(g.finale.phase, 'clear'); assert.equal(g.state, 'finishing');
  assert.ok(!g.fx.particles.some(p => p.kind === 'finishDebris'), 'CLEAR waits for the two-second debris fade');
  for (let i = 0; i < 40 && g.state === 'finishing'; i++) update(g, 0.05, {});
  assert.equal(g.state, 'won');
  assert.equal(g.coins, coins + CONFIG.escapeBonus);
  update(g, 0.05, {});
  assert.equal(g.coins, coins + CONFIG.escapeBonus);
  assert.equal(g.events.filter(e => e.type === 'end').length, 1);
});
